site_name: condor_pytorch
site_url: http://GarrettJenkinson.github.io/condor_pytorch
site_author: Garrett Jenkinson
site_description: condor_pytorch is a package implementing the CONDOR PyTorch utilities.

repo_url: https://github.com/GarrettJenkinson/condor_pytorch

#include_search: true
#theme: yeti

docs_dir: docs

theme: readthedocs

markdown_extensions:
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True # for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - extra.css

copyright: Copyright &copy; 2021 <a href="http://github.com/GarrettJenkinson">Garrett Jenkinson</a>

nav:
    - Home: index.md
    - Tutorials:
      - MNIST: tutorials/mnist.md
      - Poker Hands: tutorials/poker.md
    - API:
          - condor_pytorch.dataset: api_subpackages/condor_pytorch.dataset.md
          - condor_pytorch.losses: api_subpackages/condor_pytorch.losses.md
    - Installation: installation.md
    - Changelog: changelog.md
    - Citing: citing.md
    - License: license.md
